# Generated by Django 2.2.3 on 2019-07-10 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('submissions', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_creator.FormList')),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('input_name', models.CharField(max_length=30)),
                ('data_type', models.CharField(choices=[('TX', 'Text'), ('EML', 'Email'), ('NUM', 'Number')], max_length=3)),
                ('data', models.TextField()),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_creator.UserForm')),
            ],
        ),
    ]
