# Generated by Django 2.2.3 on 2019-07-14 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_creator', '0002_auto_20190711_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='data',
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.PositiveIntegerField()),
                ('data', models.TextField()),
                ('field_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_creator.FormField')),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_submisssions', to='form_creator.UserForm')),
            ],
        ),
    ]
