# Generated by Django 2.2.3 on 2019-07-15 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_creator', '0003_auto_20190714_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('field_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_creator.FormField')),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.PositiveIntegerField()),
                ('user_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_submission', to='form_creator.UserForm')),
            ],
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.AddField(
            model_name='fieldsubmission',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_creator.Submissions'),
        ),
    ]
