# Generated by Django 2.2.3 on 2019-07-15 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_creator', '0004_auto_20190715_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='submissions',
        ),
    ]
