# Generated by Django 2.2.3 on 2019-07-16 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_creator', '0005_remove_userform_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='user_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_submission', to='form_creator.UserForm'),
        ),
    ]
