# Generated by Django 2.2.3 on 2019-07-16 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_creator', '0007_auto_20190716_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldsubmission',
            name='field_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_creator.FormField'),
        ),
    ]
