# Generated by Django 2.2.3 on 2019-07-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_creator', '0008_auto_20190716_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='submissions',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
