# Generated by Django 2.2.3 on 2019-07-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_creator', '0010_auto_20190717_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='data_type',
            field=models.CharField(choices=[('TX', 'Text'), ('COL', 'Color'), ('DATE', 'Date'), ('EML', 'Email'), ('TEL', 'Tel'), ('NUM', 'Number')], max_length=3),
        ),
    ]
